# Generated by Django 3.2.12 on 2022-04-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='identification',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Identificación'),
        ),
    ]
