# Generated by Django 3.2.12 on 2022-04-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identification',
            field=models.CharField(max_length=12, unique=True, verbose_name='Identificación'),
        ),
    ]
