# Generated by Django 3.2.12 on 2022-04-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identification',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Identificación'),
        ),
    ]
