# Generated by Django 3.2.12 on 2022-04-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identification',
            field=models.CharField(default=121212, max_length=12, unique=True, verbose_name='Identificación'),
            preserve_default=False,
        ),
    ]
