# Generated by Django 3.2.12 on 2022-03-14 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.CharField(blank=True, max_length=36, primary_key=True, serialize=False)),
                ('amount_withdrawn', models.FloatField(verbose_name='Dinero a retirado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale_profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='withdraw_sale_profile', to='sales_profile.saleprofile', verbose_name='Perfil de usuario')),
            ],
        ),
    ]
