# Generated by Django 3.2.12 on 2022-04-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_profile', '0002_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleprofile',
            name='last_withdraw',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ultimo retiro'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount_withdrawn',
            field=models.FloatField(verbose_name='Dinero a retirar'),
        ),
    ]
