# Generated by Django 3.2.12 on 2022-04-19 03:06

from django.db import migrations, models
import published_events_deploy.apps.sales_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_profile', '0003_auto_20220418_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[(published_events_deploy.apps.sales_profile.models.WithDrawalStatus['CREATED'], 'CREATED'), (published_events_deploy.apps.sales_profile.models.WithDrawalStatus['ACCEPTED'], 'ACCEPTED'), (published_events_deploy.apps.sales_profile.models.WithDrawalStatus['DECLINED'], 'DECLINED')], default=published_events_deploy.apps.sales_profile.models.WithDrawalStatus['CREATED'], max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
