# Generated by Django 3.2.12 on 2022-05-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_profile', '0004_auto_20220418_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED')], default='CREATED', max_length=50),
        ),
    ]
