# Generated by Django 3.2.12 on 2022-03-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(blank=True, max_length=36, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=3000, null=True, upload_to='', verbose_name='Imagen')),
            ],
        ),
    ]
