# Generated by Django 3.2.12 on 2022-03-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=3000, upload_to='', verbose_name='Imagen'),
        ),
    ]
