# Generated by Django 3.2.12 on 2022-05-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=2000, upload_to='images/', verbose_name='Imagen'),
        ),
    ]
