# Generated by Django 3.2.12 on 2022-04-19 01:50

from django.db import migrations, models
import django.db.models.deletion
import published_events_deploy.apps.transactions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0017_alter_event_other_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsModel',
            fields=[
                ('id', models.CharField(blank=True, max_length=36, primary_key=True, serialize=False)),
                ('user_identification', models.CharField(max_length=12)),
                ('ticket_amount', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[(published_events_deploy.apps.transactions.models.TransactionStatus['CREATED'], 'CREATED'), (published_events_deploy.apps.transactions.models.TransactionStatus['PAYED'], 'PAYED'), (published_events_deploy.apps.transactions.models.TransactionStatus['CANCELED'], 'CANCELED')], default=published_events_deploy.apps.transactions.models.TransactionStatus['CREATED'], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.tickettype', verbose_name='Ticket de la transacción')),
            ],
        ),
    ]
