# Generated by Django 3.2.12 on 2022-04-19 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_event_other_images'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionsModel',
            new_name='Transaction',
        ),
    ]
