# Generated by Django 3.2.12 on 2022-05-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_transactionsmodel_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='meta_data',
            field=models.JSONField(default={}),
        ),
    ]
