# Generated by Django 3.2.12 on 2022-03-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20220224_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(max_length=5000, null=True, upload_to='', verbose_name='Imagen principal'),
        ),
    ]
