# Generated by Django 3.2.12 on 2022-03-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20220305_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='Dirección'),
        ),
    ]
