# Generated by Django 3.2.12 on 2022-02-18 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Tipos de eventos'},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'verbose_name': 'Tipo de tiquete', 'verbose_name_plural': 'Tipos de tiquetes'},
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickettype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
