# Generated by Django 3.2.12 on 2022-02-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220217_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='Nombre del tipo de entrada')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción corta')),
            ],
            options={
                'verbose_name': 'Categoría de event',
                'verbose_name_plural': 'Categorías de eventos',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='categories_event', to='events.Category'),
        ),
    ]
