# Generated by Django 3.2.12 on 2022-02-25 01:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 1, 53, 11, 407001, tzinfo=utc), verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 1, 53, 11, 406498, tzinfo=utc), verbose_name='Fecha de inicio'),
        ),
    ]
