# Generated by Django 3.2.12 on 2022-03-06 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='event',
            name='sell_limit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha limite de venta'),
        ),
    ]
