# Generated by Django 3.2.12 on 2022-03-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
        ('events', '0011_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='other_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_images_event', to='multimedia.image', verbose_name='Otras imagenes'),
        ),
    ]
