# Generated by Django 3.2.12 on 2022-03-14 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
        ('events', '0012_event_other_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.OneToOneField(max_length=5000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_event', to='multimedia.image', verbose_name='Imagen principal'),
        ),
    ]
