# Generated by Django 3.2.12 on 2022-04-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_alter_image_image'),
        ('events', '0016_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='other_images',
            field=models.ManyToManyField(blank=True, related_name='other_images_event', to='multimedia.Image', verbose_name='Otras imagenes'),
        ),
    ]
