# Generated by Django 3.2.12 on 2022-04-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_tickettype_ticket_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='ticket_sales',
            field=models.IntegerField(blank=True, default=0, verbose_name='Tickets vendidos'),
        ),
    ]
