# Generated by Django 3.2.12 on 2022-04-23 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_tickettype_ticket_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.CharField(blank=True, max_length=36, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('phone', models.CharField(max_length=12, verbose_name='Telefono')),
                ('identification', models.CharField(max_length=12, verbose_name='Identificación')),
                ('ticket_quantity', models.IntegerField(default=1, verbose_name='Cantidad de tickets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.tickettype', verbose_name='Ticker(Entrada)')),
            ],
        ),
    ]
