# Generated by Django 3.2.12 on 2022-05-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_assistant_security_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='security_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo de seguridad'),
        ),
    ]
